<?php 
  $pageTitle = 'KBT STEAM Curriculum - Second Karachi Biennale';
  $metaDesc = 'Learn about KBT-STEAM, a community-oriented curriculum utilizing open technology and workshop programs at Orangi Pilot Project.';
  $bodyClass = 'page-kbt-steam'; 
  include 'components/header.php'; 
?>

<!-- Page Header (Hero Area) -->
<section class="kb19-steam-hero text-center position-relative">
    <div class="kb19-steam-hero-overlay"></div>
    <div class="container position-relative z-index-2">
        <h1 class="kb19-steam-hero-title wow custom-anim-top" data-wow-duration="1.5s" data-wow-delay="0.1s">KBT-STEAM Project</h1>
        <p class="kb19-steam-hero-subtitle wow custom-anim-top" data-wow-duration="1.5s" data-wow-delay="0.25s">Science, Tech, Engineering, Art &amp; Math</p>
        
        <!-- Breadcrumbs -->
        <nav class="kb19-steam-breadcrumbs" aria-label="breadcrumb">
            <ul class="wow custom-anim-top" data-wow-duration="1.5s" data-wow-delay="0.4s">
                <li><a href="index.php">Home</a></li>
                <li><a href="kb19-projects.php">KB19 Projects</a></li>
                <li class="active" aria-current="page">KBT STEAM</li>
            </ul>
        </nav>
    </div>
</section>

<!-- Main Wrapper -->
<div class="kb19-steam-main-wrapper">
    <div class="container">
        
        <!-- Intro Header -->
        <div class="kb19-steam-intro text-center mb-5 wow custom-anim-top">
            <span class="kb19-steam-tag"><i class="fas fa-lightbulb me-2"></i>Curriculum Innovation</span>
            <h2 class="kb19-steam-section-title">Open Technology &amp; Art Education</h2>
            <p class="kb19-steam-lead">Developing community-oriented curriculum for Pakistan by combining physical science concepts with artistic expression. Organised in partnership with Goethe-Institut and Orangi Pilot Project RTI.</p>
        </div>

        <div class="row g-5">
            <!-- Left Column: Workshop and Seminar narratives -->
            <div class="col-lg-8">
                
                <!-- Section 1: Workshop -->
                <div class="kb19-steam-card mb-5 wow custom-anim-left">
                    <h3 class="steam-card-title"><i class="fas fa-tools me-2 text-primary"></i>KBT-STEAM Workshop at Orangi Pilot Project</h3>
                    <p class="text-muted small"><strong>Facilitator:</strong> Wolfgang Spahn | <strong>Participants:</strong> 30 students and 5 teachers</p>
                    <p class="kb19-steam-body-text">
                        Two projects were organized by the KBT Outreach Committee with Wolfgang Spahn and Stephen Kovats, who have been conducting open-source technology workshops in Pakistan. Over a two-day workshop at Orangi Pilot Project, participants constructed hand-cranked <strong>Energy Harvesters</strong>.
                    </p>
                    <p class="kb19-steam-body-text">
                        Focusing on physics, mechanics, and electricity, students assembled and decorated a fun, light-emitting device that runs entirely on energy generated by manually turning a motor.
                    </p>
                    
                    <!-- Carousel 1 -->
                    <div class="kb19-steam-carousel-wrap mt-4">
                        <div class="global-carousel" data-slide-show="2" data-md-slide-show="1" data-sm-slide-show="1" data-xs-slide-show="1" data-dots="true" data-arrows="true">
                            <div class="kb19-steam-slide">
                                <a href="assets/img/KB17/IMG-20190213-WA0003.jpg" class="popup-image" title="Students assembling the Energy Harvester casing">
                                    <img src="assets/img/KB17/IMG-20190213-WA0003.jpg" alt="STEAM Workshop 1" class="img-fluid rounded" loading="lazy">
                                    <div class="slide-overlay"><i class="fas fa-expand"></i></div>
                                </a>
                            </div>
                            <div class="kb19-steam-slide">
                                <a href="assets/img/KB17/IMG20190213151730.jpg" class="popup-image" title="Wolfgang Spahn demonstrating circuitry wiring">
                                    <img src="assets/img/KB17/IMG20190213151730.jpg" alt="STEAM Workshop 2" class="img-fluid rounded" loading="lazy">
                                    <div class="slide-overlay"><i class="fas fa-expand"></i></div>
                                </a>
                            </div>
                            <div class="kb19-steam-slide">
                                <a href="assets/img/KB17/DzWboH5XQAAf4ac.jpg" class="popup-image" title="Collaborative learning environment at OPP office">
                                    <img src="assets/img/KB17/DzWboH5XQAAf4ac.jpg" alt="STEAM Workshop 3" class="img-fluid rounded" loading="lazy">
                                    <div class="slide-overlay"><i class="fas fa-expand"></i></div>
                                </a>
                            </div>
                            <div class="kb19-steam-slide">
                                <a href="assets/img/KB17/WhatsApp-Image-2019-02-16-at-7.47.52-PM-5.jpeg" class="popup-image" title="Testing motor-generated currents with LEDs">
                                    <img src="assets/img/KB17/WhatsApp-Image-2019-02-16-at-7.47.52-PM-5.jpeg" alt="STEAM Workshop 4" class="img-fluid rounded" loading="lazy">
                                    <div class="slide-overlay"><i class="fas fa-expand"></i></div>
                                </a>
                            </div>
                            <div class="kb19-steam-slide">
                                <a href="assets/img/KB17/WhatsApp-Image-2019-02-16-at-7.50.02-PM.jpeg" class="popup-image" title="Group photo of students with their harvesters">
                                    <img src="assets/img/KB17/WhatsApp-Image-2019-02-16-at-7.50.02-PM.jpeg" alt="STEAM Workshop 5" class="img-fluid rounded" loading="lazy">
                                    <div class="slide-overlay"><i class="fas fa-expand"></i></div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Section 2: Seminar -->
                <div class="kb19-steam-seminar wow custom-anim-left">
                    <h3 class="steam-card-title"><i class="fas fa-university me-2 text-primary"></i>KBT-STEAM Seminar</h3>
                    <p class="text-muted small">Hosted at the Goethe Institut, Karachi for educators &amp; makers</p>
                    <p class="kb19-steam-body-text">
                        A dedicated seminar for curriculum development brought together makers working with creative technology in Karachi. Key presenter <strong>Stephen Kovats</strong> introduced the <strong>Askotec Tool Kit</strong>, containing components for STEAM education to promote maker cultures in unstructured environments.
                    </p>
                    <p class="kb19-steam-body-text">
                        Educators and technology professionals discussed the toolkit in the context of Pakistan and developed 4 scenarios for local application. This event initiated a series bringing together groups with similar curriculum development interests.
                    </p>
                    
                    <!-- Carousel 2 -->
                    <div class="kb19-steam-carousel-wrap mt-4">
                        <div class="global-carousel" data-slide-show="2" data-md-slide-show="1" data-sm-slide-show="1" data-xs-slide-show="1" data-dots="true" data-arrows="true">
                            <div class="kb19-steam-slide">
                                <a href="assets/img/KB17/IMG20190213135154.jpg" class="popup-image" title="Stephen Kovats introducing the Askotec Toolkit components">
                                    <img src="assets/img/KB17/IMG20190213135154.jpg" alt="STEAM Seminar 1" class="img-fluid rounded" loading="lazy">
                                    <div class="slide-overlay"><i class="fas fa-expand"></i></div>
                                </a>
                            </div>
                            <div class="kb19-steam-slide">
                                <a href="assets/img/KB17/IMG20190213154012.jpg" class="popup-image" title="Educators mapping out teaching scenarios">
                                    <img src="assets/img/KB17/IMG20190213154012.jpg" alt="STEAM Seminar 2" class="img-fluid rounded" loading="lazy">
                                    <div class="slide-overlay"><i class="fas fa-expand"></i></div>
                                </a>
                            </div>
                            <div class="kb19-steam-slide">
                                <a href="assets/img/KB17/IMG20190213151730-1.jpg" class="popup-image" title="Interactive technology maker discussions">
                                    <img src="assets/img/KB17/IMG20190213151730-1.jpg" alt="STEAM Seminar 3" class="img-fluid rounded" loading="lazy">
                                    <div class="slide-overlay"><i class="fas fa-expand"></i></div>
                                </a>
                            </div>
                            <div class="kb19-steam-slide">
                                <a href="assets/img/KB17/IMG20190213142008.jpg" class="popup-image" title="Detailed inspection of open-source circuit boards">
                                    <img src="assets/img/KB17/IMG20190213142008.jpg" alt="STEAM Seminar 4" class="img-fluid rounded" loading="lazy">
                                    <div class="slide-overlay"><i class="fas fa-expand"></i></div>
                                </a>
                            </div>
                            <div class="kb19-steam-slide">
                                <a href="assets/img/KB17/IMG20190213141916.jpg" class="popup-image" title="Collaborative work groups on local curriculum integration">
                                    <img src="assets/img/KB17/IMG20190213141916.jpg" alt="STEAM Seminar 5" class="img-fluid rounded" loading="lazy">
                                    <div class="slide-overlay"><i class="fas fa-expand"></i></div>
                                </a>
                            </div>
                            <div class="kb19-steam-slide">
                                <a href="assets/img/KB17/IMG20190213141846.jpg" class="popup-image" title="Wolfgang Spahn lecturing on curriculum objectives">
                                    <img src="assets/img/KB17/IMG20190213141846.jpg" alt="STEAM Seminar 6" class="img-fluid rounded" loading="lazy">
                                    <div class="slide-overlay"><i class="fas fa-expand"></i></div>
                                </a>
                            </div>
                            <div class="kb19-steam-slide">
                                <a href="assets/img/KB17/IMG20190213140727.jpg" class="popup-image" title="Assembling curriculum models for educational boards">
                                    <img src="assets/img/KB17/IMG20190213140727.jpg" alt="STEAM Seminar 7" class="img-fluid rounded" loading="lazy">
                                    <div class="slide-overlay"><i class="fas fa-expand"></i></div>
                                </a>
                            </div>
                            <div class="kb19-steam-slide">
                                <a href="assets/img/KB17/IMG-20190213-WA0003-1.jpg" class="popup-image" title="Seminar concluding session and team photo">
                                    <img src="assets/img/KB17/IMG-20190213-WA0003-1.jpg" alt="STEAM Seminar 8" class="img-fluid rounded" loading="lazy">
                                    <div class="slide-overlay"><i class="fas fa-expand"></i></div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <!-- Right Column: Leadership & Organizations -->
            <div class="col-lg-4">
                <div class="kb19-steam-sidebar wow custom-anim-right" data-wow-duration="1.2s">
                    
                    <!-- Leadership Panel -->
                    <div class="kb19-steam-leadership-box mb-4">
                        <h4 class="kb19-steam-sidebar-title"><i class="fas fa-user-tie me-2 text-primary"></i>Project Leadership</h4>
                        <p class="kb19-steam-body-text mb-0">
                            The STEAM projects are a core part of the KBT initiative since 2016, led by <strong>Atteqa Malik</strong>, Chair of the KBT Outreach Committee. These projects introduce creative open-source technologies to learners in Karachi.
                        </p>
                    </div>

                    <!-- Participating Orgs Badges -->
                    <div class="kb19-steam-orgs-box mt-4">
                        <h4 class="kb19-steam-sidebar-title"><i class="fas fa-sitemap me-2 text-primary"></i>Participating Institutions</h4>
                        <p class="text-muted small">Collaborative network of organizations that developed scenarios for Pakistan:</p>
                        
                        <div class="kb19-steam-org-badges">
                            <span class="kb19-steam-org">Ejaadtech</span>
                            <span class="kb19-steam-org">The Lyceum School</span>
                            <span class="kb19-steam-org">NJV School</span>
                            <span class="kb19-steam-org">CBM</span>
                            <span class="kb19-steam-org">Orangi Pilot Project</span>
                            <span class="kb19-steam-org">STEMERS</span>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
</div>

<?php include 'components/footer.php'; ?>
